version: '3'
services:
  app:
    build: .
    ports:
      - "8085:8085"

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.1.14:5432/faculte
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
    networks:
      - faculte-reseau

networks:
  faculte-reseau:
    driver: bridge
